// Code generated by serialize.
// source: main.go
// DO NOT EDIT!

package main

import (
	"encoding/binary"
	"unsafe"
)

var _ = unsafe.Sizeof(0)

func (i *B) SerializeLen() (n int) {
	n += 8
	n += int(unsafe.Sizeof(i.f))
	n += int(unsafe.Sizeof(i.c))
	return
}

func (i *B) Serialize(b []byte, order binary.ByteOrder) {
	order.PutUint64(b, uint64(i.i))
	b = b[8:]
	b = b[copy(b, (*(*[unsafe.Sizeof(i.f)]byte)(unsafe.Pointer(&i.f)))[:]):]
	b = b[copy(b, (*(*[unsafe.Sizeof(i.c)]byte)(unsafe.Pointer(&i.c)))[:]):]
}

func (i *B) Deserialize(b []byte, order binary.ByteOrder) {
	i.i = int(order.Uint64(b[:8]))
	b = b[8:]
	i.f = *(*float64)(unsafe.Pointer(&b[0]))
	b = b[unsafe.Sizeof(i.f):]
	i.c = *(*complex128)(unsafe.Pointer(&b[0]))
	b = b[unsafe.Sizeof(i.c):]
}
