// Code generated by serialize.
// source: main.go
// DO NOT EDIT!

package main

import (
	"encoding/binary"
	"unsafe"
)

var _ = unsafe.Sizeof(0)

func (i *C) SerializeLen() (n int) {
	n += 4
	return
}

func (i *C) Serialize(b []byte, order binary.ByteOrder) {
	order.PutUint32(b, uint32(*i))
	b = b[4:]
}

func (i *C) Deserialize(b []byte, order binary.ByteOrder) {
	f := rune(order.Uint32(b[:4]))
	b = b[4:]
	*i = C(f)
}
